parameters:
  hola: 'hola mundo desde parameters'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  ## Command Bus

  tactician.command_bus:
    class: League\Tactician\CommandBus
    arguments: [['@tactician.middleware.command_handler']]
    public: true

  tactician.middleware.command_handler:
    class: League\Tactician\Handler\CommandHandlerMiddleware
    arguments:
      - '@app.util.infrastructure.bus.name_extractor.class_name_with_suffix'
      - '@tactician.locator.callable'
      - '@tactician.inflector.handle'

  app.util.infrastructure.bus.name_extractor.class_name_with_suffix:
    class: TacticianSfDi\Infrastructure\Bus\CommandNameExtractor\ClassWithSuffix

  tactician.inflector.handle:
    class: League\Tactician\Handler\MethodNameInflector\HandleInflector

  tactician.locator.callable:
    class: League\Tactician\Handler\Locator\CallableLocator
    arguments:
      - ['@service_container', get]
