parameters:
  command_name_extractor.suffix: '.handler'

services:

  ## Command Bus
  tactician.command_bus:
    class: League\Tactician\CommandBus
    arguments: [['@tactician.middleware.command_handler']]

  tactician.middleware.command_handler:
    class: League\Tactician\Handler\CommandHandlerMiddleware
    arguments:
      - '@app.util.infrastructure.bus.name_extractor.class_name_with_suffix'
      - '@tactician.locator.callable'
      - '@tactician.inflector.handle'

  app.util.infrastructure.bus.name_extractor.class_name_with_suffix:
    class: TacticianSfDi\Infrastructure\Bus\CommandNameExtractor\ClassWithSuffix
    arguments:
      $suffix: '%command_name_extractor.suffix%'

  tactician.inflector.handle:
    class: League\Tactician\Handler\MethodNameInflector\HandleInflector

  tactician.locator.callable:
    class: League\Tactician\Handler\Locator\CallableLocator
    arguments:
      - ['@service_container', get]

  ## Handlers
  TacticianSfDi\Application\FlowsOk\FlowsOkCommand.handler:
    class: TacticianSfDi\Application\FlowsOk\FlowsOk